=== Team-Inceptus/InceptusNMS/schemas/inceptusnms.json
{
    "$id": "inceptusnms.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "definitions": {
        "javatype": {
            "type": "string",
            "enum": [
                "class",
                "interface",
                "enum",
                "record",
                "annotation"
            ],
            "description": "The Java type of the class"
        },
        "comment": {
            "type": "string",
            "description": "The JavaDoc comment value of an element"
        },
        "annotations": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "additionalProperties": true,
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "The Java type of the annotation"
                    },
                    "params": {
                        "$ref": "#/definitions/params"
                    }
                }
            }
        },
        "params": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "additionalProperties": true,
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "The Java type of the parameter"
                    },
                    "name": {
                        "type": "string",
                        "description": "The case-sensitive name of the parameter"
                    },
                    "comment": {
                        "$ref": "#/definitions/comment"
                    }
                },
                "required": [
                    "type",
                    "name",
                    "comment"
                ]
            },
            "description": "The parameters of a method or constructor"
        },
        "visbility": {
            "type": "string",
            "enum": [
                "public",
                "package",
                "protected",
                "private"
            ],
            "default": "public",
            "description": "The visbility of an element"
        },
        "mods": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "additionalProperties": false,
                "type": "string",
                "enum": [
                    "abstract",
                    "static",
                    "final",
                    "strictfp",
                    "volatile",
                    "transient"
                ]
            },
            "description": "The java modifiers of an element"
        },
        "enumeration": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name of the enum constant"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "name",
                "comment"
            ],
            "description": "Enumeration definition"
        },
        "field": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "type": {
                    "type": "string"
                },
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "mods": {
                    "$ref": "#/definitions/mods"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "type",
                "comment"
            ],
            "description": "Field definition"
        },
        "constructor": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "params": {
                    "$ref": "#/definitions/params"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "comment"
            ],
            "description": "Constructor definition"
        },
        "method": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "mods": {
                    "$ref": "#/definitions/mods"
                },
                "params": {
                    "$ref": "#/definitions/params"
                },
                "return": {
                    "type": "string",
                    "default": "void",
                    "description": "The return type of the method"
                },
                "throws": {
                    "type": "array",
                    "additionalItems": true,
                    "items": {
                        "type": "string"
                    },
                    "description": "The exceptions thrown by the method"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "comment"
            ],
            "description": "Method definition"
        }
    },
    "properties": {
        "class": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "type": {
                    "$ref": "#/definitions/javatype"
                },
                "enclosing": {
                    "type": "string",
                    "description": "The enclosing class of this class (if applicable)"
                },
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "mods": {
                    "$ref": "#/definitions/mods"
                },
                "extends": {
                    "type": "string",
                    "description": "The class this class extends (if applicable)"
                },
                "implements": {
                    "type": "array",
                    "additionalItems": true,
                    "items": {
                        "type": "string"
                    },
                    "description": "The interfaces this class implements (if applicable)"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "description": "Class definition",
            "required": [
                "type",
                "comment"
            ]
        },
        "enumerations": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "$ref": "#/definitions/enumeration"
            },
            "description": "Enumeration definitions"
        },
        "fields": {
            "type": "object",
            "additionalProperties": true,
            "patternProperties": {
                "[\\s\\S]*": {
                    "$ref": "#/definitions/field"
                }
            },
            "description": "Field definitions"
        },
        "constructors": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "$ref": "#/definitions/constructor"
            },
            "description": "Constructor definitions"
        },
        "methods": {
            "type": "object",
            "additionalProperties": true,
            "patternProperties": {
                "[\\s\\S]*": {
                    "$ref": "#/definitions/method"
                }
            },
            "description": "Method definitions"
        }
    },
    "title": "InceptusNMS Documentation",
    "description": "InceptusNMS Documentation Schema for a class docs JSON file",
    "type": "object"
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/world/entity/ai/behavior/Behavior.json
{
  "class": {
    "type": "class",
    "mods": ["abstract"],
    "implements": [
      "{pkg}.BehaviorControl<E>"
    ],
    "generics": {
      "E": {
        "extends": [
          "net.minecraft.world.entity.LivingEntity"
        ],
        "comment": "The entity type that this Behavior can use."
      }
    },
    "comment": "Represents a Behavior that can be ran."
  },
  "fields": {
    "DEFAULT_DURATION": {
      "type": "int",
      "mods": ["static", "final"],
      "value": "60",
      "comment": "The default duration for this Behavior's lifetime."
    },
    "entryCondition": {
      "type": "java.util.Map<net.minecraft.world.entity.ai.memory.MemoryModuleType<?>, net.minecraft.world.entity.ai.memory.MemoryStatus>",
      "visibility": "protected",
      "mods": ["final"],
      "comment": "The conditions for this Behavior to start."
    },
    "status": {
      "type": "{this}$Status",
      "visibility": "private",
      "comment": "The status of this Behavior."
    },
    "endTimestamp": {
      "type": "long",
      "visibility": "private",
      "comment": "The timestamp, in ticks, of when this Behavior should end."
    },
    "minDuration": {
      "type": "long",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The minimum duration of this Behavior."
    },
    "maxDuration": {
      "type": "long",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The minimum duration of this Behavior."
    }
  },
  "constructors": [
    {
      "$fields": [
        "entryCondition"
      ],
      "comment": "Constructs a new Behavior with the default run duration of `60`."
    },
    {
      "$fields": [
        "entryCondition",
        "minDuration"
      ],
      "comment": "Constructs a new Behavior with idential minimum and maximum durations."
    },
    {
      "$fields": [
        "entryCondition",
        "minDuration",
        "maxDuration"
      ],
      "comment": "Constructs a new Behavior."
    }
  ],
  "methods": {
    "start": {
      "visibility": "protected",
      "params": [
        {
          "type": "net.minecraft.world.level.ServerLevel",
          "name": "level",
          "comment": "The world to use in."
        },
        {
          "type": "E",
          "name": "entity",
          "comment": "The entity that is running this behavior."
        },
        {
          "type": "long",
          "name": "tick",
          "comment": "The current elapsed tick count."
        }
      ],
      "comment": "Runs this Behavior."
    },
    "tick": {
      "visibility": "protected",
      "params": [
        {
          "type": "net.minecraft.world.level.ServerLevel",
          "name": "level",
          "comment": "The world to use in."
        },
        {
          "type": "E",
          "name": "entity",
          "comment": "The entity that is running this behavior."
        },
        {
          "type": "long",
          "name": "tick",
          "comment": "The current elapsed tick count."
        }
      ],
      "comment": "Ticks this Behavior."
    },
    "stop": {
      "visibility": "protected",
      "params": [
        {
          "type": "net.minecraft.world.level.ServerLevel",
          "name": "level",
          "comment": "The world to use in."
        },
        {
          "type": "E",
          "name": "entity",
          "comment": "The entity that is running this behavior."
        },
        {
          "type": "long",
          "name": "tick",
          "comment": "The current elapsed tick count."
        }
      ],
      "comment": "Stops this Behavior."
    },
    "timedOut": {
      "visibility": "protected",
      "params": [
        {
          "type": "long",
          "name": "ticks",
          "comment": "The current elapsed time, in ticks."
        }
      ],
      "return": {
        "type": "boolean",
        "comment": "Whether this Behavior is currently timed out."
      },
      "comment": "Gets whether this Behavior is currently timed out."
    },
    "checkExtraStartConditions": {
      "visibility": "protected",
      "params": [
        {
          "type": "net.minecraft.world.level.ServerLevel",
          "name": "level",
          "comment": "The world to use in."
        },
        {
          "type": "E",
          "name": "entity",
          "comment": "The entity that is running this behavior."
        }
      ],
      "return": {
        "type": "boolean",
        "comment": "Whether this Behavior passed its extra conditions."
      },
      "comment": "Checks that this behavior can be ran, according to any extra conditions."
    },
    "hasRequiredMemories": {
      "visibility": "protected",
      "params": [
        {
          "type": "E",
          "name": "entity",
          "comment": "The entity that is running this behavior."
        }
      ],
      "return": {
        "type": "boolean",
        "comment": "Whether the entity has the required memories."
      },
      "comment": "Checks that the entity has the required memories to run this Behavior."
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/advancements/TreeNodePosition.json
{
  "class": {
    "type": "class",
    "comment": "Represents an @({pkg}.AdvancementNode)'s position on an Advancement Tree."
  },
  "fields": {
    "node": {
      "type": "{pkg}.AdvancementNode",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The @({pkg}.AdvancementNode) this position is for."
    },
    "parent": {
      "type": "{pkg}.AdvancementNode",
      "visibility": "private",
      "mods": ["final"],
      "annotations": [
        {
          "type": "nullable"
        }
      ],
      "comment": "The parent node of this position."
    },
    "previousSibling": {
      "type": "{pkg}.AdvancementNode",
      "visibility": "private",
      "mods": ["final"],
      "annotations": [
        {
          "type": "nullable"
        }
      ],
      "comment": "The previous sibling node for this position."
    },
    "childIndex": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The index of the child node for this position."
    },
    "children": {
      "type": "list<{this}>",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The list of children nodes that this position owns."
    },
    "ancestor": {
      "type": "{this}",
      "visibility": "private",
      "comment": "The direct ancestor node for this position."
    },
    "thread": {
      "type": "{this}",
      "visibility": "private",
      "comment": "The thread node for this position."
    },
    "x": {
      "type": "int",
      "visibility": "private",
      "comment": "The x coordinate of the position."
    },
    "y": {
      "type": "float",
      "visibility": "private",
      "comment": "The y coordinate of the position."
    },
    "mod": {
      "type": "float",
      "visibility": "private",
      "comment": "The cached mod value of the position."
    },
    "change": {
      "type": "float",
      "visibility": "private",
      "comment": "How much this position has changed before being updated."
    },
    "shift": {
      "type": "float",
      "visibility": "private",
      "comment": "How much the y position has changed before being updated."
    }
  },
  "constructors": [
    {
      "$fields": [
        "node",
        "parent",
        "previousSibling",
        "childIndex",
        "x"
      ],
      "comment": "Creates a new @({this}) with the given parameters."
    }
  ],
  "methods": {
    "addChild": {
      "visibility": "private",
      "return": {
        "type": "{this}",
        "comment": "The added child."
      },
      "annotations": [
        {
          "type": "nullable"
        }
      ],
      "comment": "Adds a child to this position."
    },
    "firstWalk": {
      "visibility": "private",
      "comment": "Walks this position and its children and sets their x and y coordinates."
    },
    "secondWalk": {
      "visibility": "private",
      "params": [
        {
          "type": "float",
          "name": "shift",
          "comment": "The amount to shift this position by in the Y direction."
        },
        {
          "type": "int",
          "name": "x",
          "comment": "The new X value."
        },
        {
          "type": "float",
          "name": "newY",
          "comment": "The new Y value."
        }
      ],
      "return": {
        "type": "float",
        "comment": "The amount this position has shifted by."
      },
      "comment": "Walks this position and its children *again* and sets their x and y coordinates."
    },
    "thirdWalk": {
      "visibility": "private",
      "params": [
        {
          "type": "float",
          "name": "shift",
          "comment": "The amount to shift this position by in the Y direction."
        }
      ],
      "comment": "Walks this position and its children *again* and changes their y coordinate."
    },
    "executeShifts": {
      "visibility": "private",
      "comment": "Executes the shifts of this position and its children."
    },
    "previousOrThread": {
      "visibility": "private",
      "return": {
        "type": "{this}",
        "comment": "The previous or thread node, or null if not found."
      },
      "annotations": [
        {
          "type": "nullable"
        }
      ],
      "comment": "Gets the previous or thread node."
    },
    "nextOrThread": {
      "visibility": "private",
      "return": {
        "type": "{this}",
        "comment": "The next or thread node, or null if not found."
      },
      "annotations": [
        {
          "type": "nullable"
        }
      ],
      "comment": "Gets the next or thread node."
    },
    "apportion": {
      "visibility": "private",
      "params": [
        {
          "type": "{this}",
          "name": "ancestor",
          "comment": "The ancestor node."
        }
      ],
      "return": {
        "type": "{this}",
        "comment": "The ancestor node inputted."
      },
      "comment": "Apportions this position."
    },
    "moveSubtree": {
      "visibility": "private",
      "params": [
        {
          "type": "{this}",
          "name": "node",
          "comment": "The node subtree to move."
        },
        {
          "type": "float",
          "name": "shift",
          "comment": "The amount to shift the node by."
        }
      ],
      "comment": "Moves the subtree of this position."
    },
    "getAncestor": {
      "visibility": "private",
      "params": [
        {
          "type": "{this}",
          "name": "node",
          "comment": "The node to get the ancestor of."
        },
        {
          "type": "{this}",
          "name": "defaultAncestor",
          "comment": "The default ancestor to return if the node has no ancestor."
        }
      ],
      "return": {
        "type": "{this}",
        "comment": "The ancestor of the node."
      },
      "comment": "Gets the ancestor of the node."
    },
    "finalizePosition": {
      "visibility": "private",
      "comment": "Finalizes the position."
    },
    "run": {
      "mods": ["static"],
      "params": [
        {
          "type": "{pkg}.AdvancementNode",
          "name": "root",
          "comment": "The root node."
        }
      ],
      "comment": "Runs the algorithm on the given root node.\nThese actions position the given node correctly on an Advancement Tree."
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/resources/ResourceKey.json
{
  "class": {
    "type": "class",
    "generics": {
      "T": {
        "comment": "The type of the registry entry."
      }
    },
    "comment": "Utility class that holds a ResourceLocation linked to a registry."
  },
  "fields": {
    "VALUES": {
      "type": "java.util.concurrent.ConcurrentMap<{this}$InternKey, {this}<?>>",
      "visibility": "private",
      "mods": ["static", "final"],
      "comment": "The map of all registered entries."
    },
    "registryName": {
      "type": "{pkg}.ResourceLocation",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The registry name of this entry."
    },
    "location": {
      "type": "{pkg}.ResourceLocation",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The location of this entry."
    }
  },
  "constructors": [
    {
      "visibility": "private",
      "$fields": [
        "registryName",
        "location"
      ],
      "comment": "Creates a new entry for the given registry."
    }
  ],
  "methods": {
    "codec": {
      "mods": ["static"],
      "params": [
        {
          "type": "{this}<? extends net.minecraft.core.Registry<T>>",
          "name": "registry",
          "comment": "The registry to get the codec for."
        }
      ],
      "generics": {
        "T": {
          "comment": "The type of the registry entry."
        }
      },
      "return": {
        "type": "codec<{this}<T>>",
        "comment": "The codec for the given registry."
      },
      "comment": "Gets the codec for the given registry."
    },
    "create": [
      {
        "mods": ["static"],
        "params": [
          {
            "type": "{this}<? extends net.minecraft.core.Registry<T>>",
            "name": "registry",
            "comment": "The registry to create the entry for."
          },
          {
            "type": "{pkg}.ResourceLocation",
            "name": "location",
            "comment": "The location of the entry."
          }
        ],
        "generics": {
          "T": {
            "comment": "The type of the registry entry."
          }
        },
        "return": {
          "type": "{this}<T>",
          "comment": "The created entry."
        },
        "comment": "Creates a new entry for the given registry."
      },
      {
        "visibility": "private",
        "mods": ["static"],
        "params": [
          {
            "type": "{pkg}.ResourceLocation",
            "name": "registryName",
            "comment": "The registry name of the entry."
          },
          {
            "type": "{pkg}.ResourceLocation",
            "name": "location",
            "comment": "The location of the entry."
          }
        ],
        "generics": {
          "T": {
            "comment": "The type of the registry entry."
          }
        },
        "return": {
          "type": "{this}<T>",
          "comment": "The created entry."
        },
        "comment": "Creates a new entry for the given registry."
      }
    ],
    "createRegistryKey": {
      "mods": ["static"],
      "params": [
        {
          "type": "{pkg}.ResourceLocation",
          "name": "registryName",
          "comment": "The registry name of the entry."
        }
      ],
      "return": {
        "type": "{this}<net.minecraft.core.Registry<T>>",
        "comment": "The registry key for the given registry name."
      },
      "comment": "Creates a new registry key for the given registry name."
    },
    "isFor": {
      "params": [
        {
          "type": "{this}<? extends net.minecraft.core.Registry<T>>",
          "name": "registry",
          "comment": "The registry to check."
        }
      ],
      "return": {
        "type": "boolean",
        "comment": "True if this entry is for the given registry."
      },
      "comment": "Checks if this entry is for the given registry."
    },
    "cast": {
      "params": [
        {
          "type": "{this}<? extends net.minecraft.core.Registry<E>>",
          "name": "registry",
          "comment": "The registry to cast to."
        }
      ],
      "generics": {
        "E": {
          "comment": "The type of the registry entry."
        }
      },
      "return": {
        "type": "java.util.Optional<{this}<E>>",
        "comment": "This entry casted to the given registry."
      },
      "comment": "Casts this entry to the given registry."
    },
    "location": {
      "$getter": "location"
    },
    "registry": {
      "$getter": "registryName"
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/world/entity/MobCategory.json
{
  "class": {
    "type": "enum",
    "implements": [
      "net.minecraft.util.StringRepresentable"
    ],
    "comment": "Represents a category for a @({pkg}.Mob) entity."
  },
  "enumerations": [
    {
      "name": "MONSTER",
      "comment": "A hostile mob that usually attacks the player."
    },
    {
      "name": "CREATURE",
      "comment": "An entity with simple ai."
    },
    {
      "name": "AMBIENT",
      "comment": "An entity that is usually aesthetical and provides no significant functionality."
    },
    {
      "name": "AXOLOTLS",
      "comment": "An axolotl mob."
    },
    {
      "name": "UNDERGROUND_WATER_CREATURE",
      "comment": "A water creature that spawns underground."
    },
    {
      "name": "WATER_CREATURE",
      "comment": "A water creature that spawns in the water."
    },
    {
      "name": "WATER_AMBIENT",
      "comment": "An ambient water creature."
    },
    {
      "name": "MISC",
      "comment": "A miscellaneous mob."
    }
  ],
  "fields": {
    "noDespawnDistance": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "value": "32",
      "comment": "The maximum distance from which the mob will not despawn."
    },
    "CODEC": {
      "type": "codec<{this}>",
      "mods": ["static", "final"],
      "comment": "A codec for this enum."
    },
    "max": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The maximum amount of entities in this category that can be present in a single chunk."
    },
    "isFriendly": {
      "type": "boolean",
      "visibility": "private",
      "mods": ["final"],
      "comment": "Whether this category is friendly towards players."
    },
    "isPersistent": {
      "type": "boolean",
      "visibility": "private",
      "mods": ["final"],
      "comment": "Whether this category is persistent."
    },
    "name": {
      "type": "string",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The name of this category."
    },
    "despawnDistance": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The maximum distance from which the mob will despawn."
    }
  },
  "constructors": [
    {
      "$fields": [
        "name",
        "max",
        "isFriendly",
        "isPersistent",
        "despawnDistance"
      ],
      "comment": "Constructs a new MobCategory."
    }
  ],
  "methods": {
    "getName": {
      "$getter": "name"
    },
    "getMaxInstancesPerChunk": {
      "$getter": "max"
    },
    "isFriendly": {
      "$getter": "isFriendly"
    },
    "isPersistent": {
      "$getter": "isPersistent"
    },
    "getDespawnDistance": {
      "$getter": "despawnDistance"
    },
    "getNoDespawnDistance": {
      "$getter": "noDespawnDistance"
    }
  }
}
