=== Team-Inceptus/InceptusNMS/schemas/inceptusnms.json
{
    "$id": "inceptusnms.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "definitions": {
        "javatype": {
            "type": "string",
            "enum": [
                "class",
                "interface",
                "enum",
                "record",
                "annotation"
            ],
            "description": "The Java type of the class"
        },
        "comment": {
            "type": "string",
            "description": "The JavaDoc comment value of an element"
        },
        "annotations": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "additionalProperties": true,
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "The Java type of the annotation"
                    },
                    "params": {
                        "$ref": "#/definitions/params"
                    }
                }
            }
        },
        "params": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "additionalProperties": true,
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "The Java type of the parameter"
                    },
                    "name": {
                        "type": "string",
                        "description": "The case-sensitive name of the parameter"
                    },
                    "comment": {
                        "$ref": "#/definitions/comment"
                    }
                },
                "required": [
                    "type",
                    "name",
                    "comment"
                ]
            },
            "description": "The parameters of a method or constructor"
        },
        "visbility": {
            "type": "string",
            "enum": [
                "public",
                "package",
                "protected",
                "private"
            ],
            "default": "public",
            "description": "The visbility of an element"
        },
        "mods": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "additionalProperties": false,
                "type": "string",
                "enum": [
                    "abstract",
                    "static",
                    "final",
                    "strictfp",
                    "volatile",
                    "transient"
                ]
            },
            "description": "The java modifiers of an element"
        },
        "enumeration": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name of the enum constant"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "name",
                "comment"
            ],
            "description": "Enumeration definition"
        },
        "field": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "type": {
                    "type": "string"
                },
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "mods": {
                    "$ref": "#/definitions/mods"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "type",
                "comment"
            ],
            "description": "Field definition"
        },
        "constructor": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "params": {
                    "$ref": "#/definitions/params"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "comment"
            ],
            "description": "Constructor definition"
        },
        "method": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "mods": {
                    "$ref": "#/definitions/mods"
                },
                "params": {
                    "$ref": "#/definitions/params"
                },
                "return": {
                    "type": "string",
                    "default": "void",
                    "description": "The return type of the method"
                },
                "throws": {
                    "type": "array",
                    "additionalItems": true,
                    "items": {
                        "type": "string"
                    },
                    "description": "The exceptions thrown by the method"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "comment"
            ],
            "description": "Method definition"
        }
    },
    "properties": {
        "class": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "type": {
                    "$ref": "#/definitions/javatype"
                },
                "enclosing": {
                    "type": "string",
                    "description": "The enclosing class of this class (if applicable)"
                },
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "mods": {
                    "$ref": "#/definitions/mods"
                },
                "extends": {
                    "type": "string",
                    "description": "The class this class extends (if applicable)"
                },
                "implements": {
                    "type": "array",
                    "additionalItems": true,
                    "items": {
                        "type": "string"
                    },
                    "description": "The interfaces this class implements (if applicable)"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "description": "Class definition",
            "required": [
                "type",
                "comment"
            ]
        },
        "enumerations": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "$ref": "#/definitions/enumeration"
            },
            "description": "Enumeration definitions"
        },
        "fields": {
            "type": "object",
            "additionalProperties": true,
            "patternProperties": {
                "[\\s\\S]*": {
                    "$ref": "#/definitions/field"
                }
            },
            "description": "Field definitions"
        },
        "constructors": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "$ref": "#/definitions/constructor"
            },
            "description": "Constructor definitions"
        },
        "methods": {
            "type": "object",
            "additionalProperties": true,
            "patternProperties": {
                "[\\s\\S]*": {
                    "$ref": "#/definitions/method"
                }
            },
            "description": "Method definitions"
        }
    },
    "title": "InceptusNMS Documentation",
    "description": "InceptusNMS Documentation Schema for a class docs JSON file",
    "type": "object"
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/CrashReport.json
{
  "class": {
    "type": "class",
    "comment": "Represents a Crash Report for the game."
  },
  "fields": {
    "LOGGER": {
      "type": "org.slf4j.Logger",
      "visibility": "private",
      "mods": ["static", "final"],
      "comment": "The logger for this class."
    },
    "DATE_TIME_FORMATTER": {
      "type": "java.time.format.DateTimeFormatter",
      "visibility": "private",
      "mods": ["static", "final"],
      "value": "yyyy-MM-dd HH:mm:ss",
      "comment": "The format for date and time."
    },
    "title": {
      "type": "string",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The title of this crash report"
    },
    "exception": {
      "type": "java.lang.Throwable",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The exception thrown for this crash report."
    },
    "details": {
      "type": "list<{pkg}.CrashReportCategory>",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The details of the Crash Report."
    },
    "saveFile": {
      "type": "file",
      "visibility": "private",
      "comment": "The file this CrashReport will be saved to."
    },
    "trackingStackTrace": {
      "type": "boolean",
      "visibility": "private",
      "comment": "Whether this Crash Report is tracking the stack trace."
    },
    "uncategorizedStackTrace": {
      "type": "java.lang.StackTraceElement[]",
      "visibility": "private",
      "comment": "An array of StackTraceElements that are not categorized."
    },
    "systemReport": {
      "type": "{pkg}.SystemReport",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The system report for this crash report."
    }
  },
  "constructors": [
    {
      "$fields": [
        "title",
        "exception"
      ],
      "comment": "Constructs a new CrashReport."
    }
  ],
  "methods": {
    "addCategory": [
      {
        "params": [
          {
            "type": "string",
            "name": "category",
            "comment": "The category to add"
          },
          {
            "type": "int",
            "name": "priority",
            "comment": "The priority of the category"
          }
        ],
        "return": {
          "type": "{pkg}.CrashReportCategory",
          "comment": "The category that was added."
        },
        "comment": "Adds a category to this Crash Report."
      },
      {
        "params": [
          {
            "type": "string",
            "name": "category",
            "comment": "The category to add"
          }
        ],
        "return": {
          "type": "net.minecraft.CrashReportCategory",
          "comment": "The category that was added."
        },
        "comment": "Adds a category to this Crash Report."
      }
    ],
    "forThrowable": {
      "mods": ["static"],
      "params": [
        {
          "type": "java.lang.Throwable",
          "name": "throwable",
          "comment": "The throwable to create a Crash Report for."
        },
        {
          "type": "string",
          "name": "title",
          "comment": "The title of the Crash Report."
        }
      ],
      "return": {
        "type": "{this}",
        "comment": "The Crash Report for the throwable."
      },
      "comment": "Creates a Crash Report for a throwable."
    },
    "getDetails": [
      {
        "params": [
          {
            "type": "java.lang.StringBuilder",
            "name": "builder",
            "comment": "The StringBuilder to append to."
          }
        ],
        "comment": "Appends the details of this Crash Report to a StringBuilder."
      },
      {
        "$getter": "details",
        "return": {
          "type": "string",
          "comment": "The details of this Crash Report, as a string."
        }
      }
    ],
    "getErrorComment": {
      "visibility": "private",
      "mods": ["static"],
      "return": {
        "type": "string",
        "comment": "The internal error comment."
      },
      "comment": "Gets the internal error comment."
    },
    "getException": {
      "$getter": "exception"
    },
    "getExceptionMessage": {
      "return": {
        "type": "string",
        "comment": "The human-readable exception message."
      },
      "comment": "Gets the human-readable exception message."
    },
    "getFriendlyReport": {
      "return": {
        "type": "string",
        "comment": "The friendly report."
      },
      "comment": "Generates a string containing a human-friendly report."
    },
    "getSaveFile": {
      "$getter": "saveFile"
    },
    "getSystemReport": {
      "$getter": "systemReport"
    },
    "getTitle": {
      "$getter": "title"
    },
    "preload": {
      "mods": ["static"],
      "comment": "Preloads this class."
    },
    "saveToFile": {
      "params": [
        {
          "type": "file",
          "name": "file",
          "comment": "The file to save to."
        }
      ],
      "return": {
        "type": "boolean",
        "comment": "Whether the save was successful."
      },
      "comment": "Saves this Crash Report to a file."
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/org/spigotmc/WatchdogThread.json
{
  "class": {
    "type": "class",
    "comment": "The Spigot Watchdog Thread."
  },
  "fields": {
    "instance": {
      "type": "{this}",
      "visibility": "private",
      "mods": ["static"],
      "comment": "The singleton instance of the Watchdog Thread."
    },
    "timeoutTime": {
      "type": "long",
      "visibility": "private",
      "comment": "The timeout time in milliseconds."
    },
    "restart": {
      "type": "boolean",
      "visibility": "private",
      "comment": "Whether or not the thread should restart after a crash."
    },
    "lastTick": {
      "type": "long",
      "visibility": "private",
      "mods": ["volatile"],
      "comment": "The last tick time in milliseconds."
    },
    "stopping": {
      "type": "boolean",
      "visibility": "private",
      "mods": ["volatile"],
      "comment": "Whether or not the thread is stopping."
    }
  },
  "constructors": [
    {
      "visibility": "private",
      "params": [
        {
          "type": "long",
          "name": "timeoutTime",
          "comment": "The timeout time in milliseconds."
        },
        {
          "type": "boolean",
          "name": "restart",
          "comment": "Whether or not the thread should restart after a crash."
        }
      ],
      "comment": "Creates a new Watchdog Thread."
    }
  ],
  "methods": {
    "monotonicMillis": {
      "visibility": "private",
      "mods": ["static"],
      "return": {
        "type": "long",
        "comment": "The current nano time in milliseconds."
      },
      "comment": "Gets the current nano time in milliseconds."
    },
    "doStart": {
      "mods": ["static"],
      "params": [
        {
          "type": "int",
          "name": "timeoutTime",
          "comment": "The timeout time in milliseconds."
        },
        {
          "type": "boolean",
          "name": "restart",
          "comment": "Whether or not the thread should restart after a crash."
        }
      ],
      "comment": "Starts the Watchdog Thread."
    },
    "tick": {
      "mods": ["static"],
      "comment": "Ticks the Watchdog Thread."
    },
    "doStop": {
      "mods": ["static"],
      "comment": "Stops the Watchdog Thread."
    },
    "run": {
      "comment": "Runs the Watchdog Thread."
    },
    "dumpThread": {
      "visibility": "private",
      "mods": ["static"],
      "params": [
        {
          "type": "java.lang.management.ThreadInfo",
          "name": "info",
          "comment": "The ThreadInfo to dump."
        },
        {
          "type": "java.util.logging.Logger",
          "name": "logger",
          "comment": "The logger to dump to."
        }
      ],
      "comment": "Dumps the ThreadInfo to the logger."
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/nbt/NbtAccounter.json
{
  "class": {
    "type": "class",
    "comment": "Utility class for counting bytes in a NBT Tag."
  },
  "fields": {
    "MAX_STACK_DEPTH": {
      "type": "int",
      "visibility": "private",
      "mods": ["static", "final"],
      "value": "512",
      "comment": "The maximum stack depth."
    },
    "quota": {
      "type": "long",
      "mods": ["final"],
      "comment": "The quota of bytes that can be read."
    },
    "usage": {
      "type": "long",
      "visibility": "private",
      "comment": "The number of bytes that have been read."
    },
    "maxDepth": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The maximum depth of the stack."
    },
    "depth": {
      "type": "int",
      "visibility": "private",
      "comment": "The current depth of the stack."
    }
  },
  "constructors": [
    {
      "$fields": [
        "quota",
        "maxDepth"
      ],
      "comment": "Constructs a new NbtAccounter."
    }
  ],
  "methods": {
    "create": {
      "mods": ["static"],
      "params": [
        {
          "type": "long",
          "name": "quota",
          "comment": "The quota of bytes that can be read."
        }
      ],
      "return": {
        "type": "{this}",
        "comment": "A new NbtAccounter."
      },
      "comment": "Creates a new NbtAccounter."
    },
    "unlimitedHeap": {
      "mods": ["static"],
      "return": {
        "type": "{this}",
        "comment": "A new NbtAccounter with an unlimited quota."
      },
      "comment": "Creates a new NbtAccounter with an unlimited quota."
    },
    "accountBytes": [
      {
        "params": [
          {
            "type": "long",
            "name": "bytes",
            "comment": "The number of bytes to account for."
          },
          {
            "type": "long",
            "name": "size",
            "comment": "The size of each byte."
          }
        ],
        "comment": "Accounts for the given number of bytes."
      },
      {
        "params": [
          {
            "type": "long",
            "name": "bytes",
            "comment": "The number of bytes to account for."
          }
        ],
        "comment": "Accounts for the given number of bytes."
      }
    ],
    "pushDepth": {
      "comment": "Pushes the current depth of the stack."
    },
    "popDepth": {
      "comment": "Pops the current depth of the stack."
    },
    "getUsage": {
      "$getter": "usage",
      "annotations": [
        {
          "type": "com.google.common.annotations.VisibleForTesting"
        }
      ]
    },
    "getDepth": {
      "$getter": "depth",
      "annotations": [
        {
          "type": "com.google.common.annotations.VisibleForTesting"
        }
      ]
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/network/PacketDecoder.json
{
  "class": {
    "type": "class",
    "extends": "io.netty.handler.codec.ByteToMessageDecoder",
    "implements": [
      "net.minecraft.network.ProtocolSwampHandler"
    ],
    "comment": "Utility class for decoding the contents of a Packet."
  },
  "fields": {
    "LOGGER": {
      "type": "org.slf4j.Logger",
      "visibility": "private",
      "mods": ["static", "final"],
      "comment": "The logger for this class."
    },
    "codecKey": {
      "type": "io.netty.util.AttributeKey<net.minecraft.network.ConnectionProtocol$CodecData>",
      "comment": "The codec key to use."
    }
  },
  "constructors": [
    {
      "params": [
        {
          "type": "io.netty.util.AttributeKey<net.minecraft.network.ConnectionProtocol$CodecData>",
          "name": "codecKey",
          "comment": "The codec key to use."
        }
      ],
      "comment": "Constructs a new PacketDecoder."
    }
  ],
  "methods":{
    "decode": {
      "visibility": "protected",
      "params": [
        {
          "type": "io.netty.channel.ChannelHandlerContext",
          "name": "context",
          "comment": "The handler context to use."
        },
        {
          "type": "io.netty.buffer.ByteBuf",
          "name": "buffer",
          "comment": "The Byte Buffer to use."
        },
        {
          "type": "java.util.List<obj>",
          "name": "list",
          "comment": "The list to add the decoded object to."
        }
      ],
      "throws": [
        {
          "type": "java.lang.Exception",
          "comment": "if the packet is invalid"
        }
      ],
      "comment": "Decodes a ByteBuf into a Packet."
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/core/GlobalPos.json
{
  "class": {
    "type": "class",
    "mods": ["final"],
    "comment": "Represents a @(net.minecraft.core.BlockPos) currently linked to a World."
  },
  "fields": {
    "CODEC": {
      "type": "codec",
      "mods": ["static", "final"],
      "comment": "The Codec for this GlobalPos."
    },
    "dimension": {
      "type": "net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>",
      "visbility": "private",
      "mods": ["final"],
      "comment": "The Resource Key of the World this GlobalPos belongs in."
    },
    "pos": {
      "type": "net.minecraft.core.BlockPos",
      "visbility": "private",
      "mods": ["final"],
      "comment": "The BlockPos position that represents this GlobalPos's coordinates."
    }
  },
  "constructors": [
    {
      "visbility": "private",
      "params": [
        {
          "type": "net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>",
          "name": "dimension",
          "comment": "The Resource Key of the World this GlobalPos belongs in."
        },
        {
          "type": "net.minecraft.core.BlockPos",
          "name": "pos",
          "comment": "The BlockPos position that represents this GlobalPos's coordinates."
        }
      ],
      "comment": "Constructs a new GlobalPos."
    }
  ],
  "methods": {
    "of": {
      "mods": ["static"],
      "params": [
        {
          "type": "net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>",
          "name": "dimension",
          "comment": "The Resource Key of the World this GlobalPos belongs in."
        },
        {
          "type": "net.minecraft.core.BlockPos",
          "name": "pos",
          "comment": "The BlockPos position that represents this GlobalPos's coordinates."
        }
      ],
      "return": "<this>",
      "comment": "Constructs a new GlobalPos."
    },
    "dimension": {
      "return": "net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level>",
      "comment": "Fetches the Resource Key of the World this GlobalPos belongs in."
    },
    "pos": {
      "return": "net.minecraft.core.BlockPos",
      "comment": "Fetches the BlockPos position that represents this GlobalPos's coordinates."
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/DetectedVersion.json
{
  "class": {
      "type": "class",
      "implements": [
        "net.minecraft.WorldVersion"
      ],
      "comment": "The default implementation of WorldVersion that automatically detects the protocl and server version."
  },
  "fields": {
    "LOGGER": {
      "type": "org.slf4j.Logger",
      "visibility": "private",
      "mods": ["static", "final"],
      "comment": "The logger for this class."
    },
    "BUILT_IN": {
      "type": "net.minecraft.WorldVersion",
      "mods": ["static", "final"],
      "comment": "The built in minecraft version."
    },
    "id": {
      "type": "string",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The Unique Identifier of this Server's Version, as a trimmed UUID string."
    },
    "name": {
      "type": "string",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The Friendly Name of this Server's Version, such as \"1.20.2\"."
    },
    "stable": {
      "type": "boolean",
      "visibility": "private",
      "mods": ["final"],
      "comment": "Whether or not this Server's Version is considered stable."
    },
    "worldVersion": {
      "type": "net.minecraft.WorldVersion",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The WorldVersion of this Server's Version."
    },
    "protocolVersion": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The Protocol Version of this Server's Version."
    },
    "resourcePackVersion": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The Resource Pack Version ID of this Server's Version."
    },
    "dataPackVersion": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The Data Pack Version ID of this Server's Version."
    },
    "buildTime": {
      "type": "date",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The Build Time of this Server's Version."
    }
  },
  "constructors": [
    {
      "visibility": "private",
      "comment": "Constructs a new DetectedVersion using hard-coded parameters."
    },
    {
      "visibility": "private",
      "params": [
        {
          "type": "com.google.gson.JsonObject",
          "name": "json",
          "comment": "The JSON Object to read from."
        }
      ],
      "comment": "Constructs a new DetectedVersion using the given JSON Object. The inputted object is directly read from <code>version.json</code>, a file stored in the server JAR."
    }
  ],
  "methods": {
    "tryDetectVersion": {
      "mods": ["static"],
      "return": {
        "type": "net.minecraft.WorldVersion",
        "comment": "The detected version, or the built-in version if the version cannot be detected."
      },
      "comment": "Attempts to detect the version of the server. If the version cannot be detected, the built-in version is returned."
    }
  }
}
