=== Team-Inceptus/InceptusNMS/schemas/inceptusnms.json
{
    "$id": "inceptusnms.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "definitions": {
        "javatype": {
            "type": "string",
            "enum": [
                "class",
                "interface",
                "enum",
                "record",
                "annotation"
            ],
            "description": "The Java type of the class"
        },
        "comment": {
            "type": "string",
            "description": "The JavaDoc comment value of an element"
        },
        "annotations": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "additionalProperties": true,
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "The Java type of the annotation"
                    },
                    "params": {
                        "$ref": "#/definitions/params"
                    }
                }
            }
        },
        "params": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "additionalProperties": true,
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string",
                        "description": "The Java type of the parameter"
                    },
                    "name": {
                        "type": "string",
                        "description": "The case-sensitive name of the parameter"
                    },
                    "comment": {
                        "$ref": "#/definitions/comment"
                    }
                },
                "required": [
                    "type",
                    "name",
                    "comment"
                ]
            },
            "description": "The parameters of a method or constructor"
        },
        "visbility": {
            "type": "string",
            "enum": [
                "public",
                "package",
                "protected",
                "private"
            ],
            "default": "public",
            "description": "The visbility of an element"
        },
        "mods": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "additionalProperties": false,
                "type": "string",
                "enum": [
                    "abstract",
                    "static",
                    "final",
                    "strictfp",
                    "volatile",
                    "transient"
                ]
            },
            "description": "The java modifiers of an element"
        },
        "enumeration": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name of the enum constant"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "name",
                "comment"
            ],
            "description": "Enumeration definition"
        },
        "field": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "type": {
                    "type": "string"
                },
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "mods": {
                    "$ref": "#/definitions/mods"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "type",
                "comment"
            ],
            "description": "Field definition"
        },
        "constructor": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "params": {
                    "$ref": "#/definitions/params"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "comment"
            ],
            "description": "Constructor definition"
        },
        "method": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "mods": {
                    "$ref": "#/definitions/mods"
                },
                "params": {
                    "$ref": "#/definitions/params"
                },
                "return": {
                    "type": "string",
                    "default": "void",
                    "description": "The return type of the method"
                },
                "throws": {
                    "type": "array",
                    "additionalItems": true,
                    "items": {
                        "type": "string"
                    },
                    "description": "The exceptions thrown by the method"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "required": [
                "comment"
            ],
            "description": "Method definition"
        }
    },
    "properties": {
        "class": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "type": {
                    "$ref": "#/definitions/javatype"
                },
                "enclosing": {
                    "type": "string",
                    "description": "The enclosing class of this class (if applicable)"
                },
                "visbility": {
                    "$ref": "#/definitions/visbility"
                },
                "mods": {
                    "$ref": "#/definitions/mods"
                },
                "extends": {
                    "type": "string",
                    "description": "The class this class extends (if applicable)"
                },
                "implements": {
                    "type": "array",
                    "additionalItems": true,
                    "items": {
                        "type": "string"
                    },
                    "description": "The interfaces this class implements (if applicable)"
                },
                "annotations": {
                    "$ref": "#/definitions/annotations"
                },
                "comment": {
                    "$ref": "#/definitions/comment"
                }
            },
            "description": "Class definition",
            "required": [
                "type",
                "comment"
            ]
        },
        "enumerations": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "$ref": "#/definitions/enumeration"
            },
            "description": "Enumeration definitions"
        },
        "fields": {
            "type": "object",
            "additionalProperties": true,
            "patternProperties": {
                "[\\s\\S]*": {
                    "$ref": "#/definitions/field"
                }
            },
            "description": "Field definitions"
        },
        "constructors": {
            "type": "array",
            "additionalItems": true,
            "items": {
                "$ref": "#/definitions/constructor"
            },
            "description": "Constructor definitions"
        },
        "methods": {
            "type": "object",
            "additionalProperties": true,
            "patternProperties": {
                "[\\s\\S]*": {
                    "$ref": "#/definitions/method"
                }
            },
            "description": "Method definitions"
        }
    },
    "title": "InceptusNMS Documentation",
    "description": "InceptusNMS Documentation Schema for a class docs JSON file",
    "type": "object"
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/nbt/IntTag.json
{
  "class": {
    "type": "class",
    "extends": "net.minecraft.nbt.NumericTag",
    "comment": "Represents a NBT Tag for a standard @(wint)."
  },
  "fields": {
    "SELF_SIZE_IN_BYTES": {
      "type": "int",
      "visibility": "private",
      "mods": ["static", "final"],
      "value": "12",
      "comment": "The size in bytes of a @(wint) tag."
    },
    "TYPE": {
      "type": "net.minecraft.nbt.TagType<{this}>",
      "mods": ["static", "final"],
      "comment": "The type of tag this class represents."
    },
    "ZERO": {
      "type": "{this}",
      "mods": ["static", "final"],
      "comment": "A @({this}) with a value of `0`."
    },
    "data": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The value of this tag as an int."
    }
  },
  "constructors": [
    {
      "visibility": "package",
      "params": [
        {
          "type": "int",
          "name": "data",
          "comment": "The value of this tag as an int."
        }
      ],
      "comment": "Creates a new @(wint) tag with the given value."
    }
  ],
  "methods": {
    "valueOf": [
      {
        "mods": ["static"],
        "params": [
          {
            "type": "int",
            "name": "data",
            "comment": "The value of this tag as an int."
          }
        ],
        "return": {
          "type": "{this}",
          "comment": "A new @(wint) tag with the given value."
        },
        "comment": "Returns a new @(wint) tag with the given value."
      }
    ]
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/server/level/Ticket.json
{
  "class": {
    "type": "class",
    "implements": [
      "java.lang.Comparable<{this}>"
    ],
    "generics": {
      "T": {
        "comment": "The holder type this Ticket has."
      }
    },
    "comment": "Utility class for representing a ticket, which keeps an element loaded."
  },
  "fields": {
    "type": {
      "type": "net.minecraft.server.level.TicketType<T>",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The type of Ticket that this object represents."
    },
    "ticketLevel": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The level of this ticket."
    },
    "key": {
      "type": "T",
      "mods": ["final"],
      "comment": "The key that holds this Ticket."
    },
    "createdTick": {
      "type": "long",
      "visibility": "private",
      "comment": "The tick this Ticket was created on."
    }
  },
  "constructors": [
    {
      "visibility": "protected",
      "params": [
        {
          "type": "net.minecraft.server.level.TicketType<T>",
          "name": "type",
          "comment": "The type of this Ticket."
        },
        {
          "type": "int",
          "name": "ticketLevel",
          "comment": "The level of this ticket."
        },
        {
          "type": "T",
          "name": "key",
          "comment": "The holder of this ticket."
        }
      ],
      "comment": "Constructs a new Ticket."
    }
  ],
  "methods": {
    "getType": {
      "$getter": "type"
    },
    "getTicketLevel": {
      "$getter": "level"
    },
    "setCreatedTick": {
      "$setter": "createdTick",
      "visibility": "protected"
    },
    "timedOut": {
      "visibility": "protected",
      "params": [
        {
          "type": "long",
          "name": "tickCount",
          "comment": "The current count of ticks."
        }
      ],
      "return": {
        "type": "boolean",
        "comment": "Whether this ticket is currently timed out."
      },
      "comment": "Gets whether this Ticket has been timed out."
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/world/phys/Vec2.json
{
  "class": {
    "type": "class",
    "comment": "Represents a 2-dimensional Vector."
  },
  "fields": {
    "ZERO": {
      "type": "{this}",
      "mods": ["static", "final"],
      "comment": "A @({this}) with both angles set to `0.0F`."
    },
    "ONE": {
      "type": "{this}",
      "mods": ["static", "final"],
      "comment": "A @({this}) with both angles set to `1.0F`."
    },
    "UNIT_X": {
      "type": "{this}",
      "mods": ["static", "final"],
      "comment": "A @({this}) with x set to `1.0F`."
    },
    "NEG_UNIT_X": {
      "type": "{this}",
      "mods": ["static", "final"],
      "comment": "A @({this}) with x set to `-1.0F`."
    },
    "UNIT_Y": {
      "type": "{this}",
      "mods": ["static", "final"],
      "comment": "A @({this}) with y set to `1.0F`."
    },
    "NEG_UNIT_Y": {
      "type": "{this}",
      "mods": ["static", "final"],
      "comment": "A @({this}) with y set to `-1.0F`."
    },
    "MAX": {
      "type": "{this}",
      "mods": ["static", "final"],
      "comment": "A @({this}) with both angles set to @(java.lang.Float#MAX_VALUE)."
    },
    "MIN": {
      "type": "{this}",
      "mods": ["static", "final"],
      "comment": "A @({this}) with both angles set to @(java.lang.Float#MIN_VALUE)."
    },
    "x": {
      "type": "float",
      "mods": ["final"],
      "comment": "The x angle for this 2D Vector."
    },
    "y": {
      "type": "float",
      "mods": ["final"],
      "comment": "The y angle for this 2D Vector."
    }
  },
  "constructors": [
    {
      "params": [
        {
          "type": "float",
          "name": "x",
          "comment": "The x angle for this 2D Vector."
        },
        {
          "type": "float",
          "name": "y",
          "comment": "The y angle for this 2D Vector."
        }
      ],
      "comment": "Constructs a new 2D Vector."
    }
  ],
  "methods": {
    "scale": {
      "params": [
        {
          "type": "float",
          "name": "scale",
          "comment": "The scale to use on the 2D Vector."
        }
      ],
      "return": {
        "type": "{this}",
        "comment": "The newly scaled vector."
      },
      "comment": "Scales this 2D Vector."
    },
    "dot": {
      "params": [
        {
          "type": "{this}",
          "name": "vector",
          "comment": "The other vector to perform the operation."
        }
      ],
      "return": {
        "type": "float",
        "comment": "The dot product of both vectors."
      },
      "comment": "Gets the dot product of both vectors."
    },
    "add": [
      {
        "params": [
          {
            "type": "{this}",
            "name": "vector",
            "comment": "The other vector to add to this one."
          }
        ],
        "return": {
          "type": "{this}",
          "comment": "The vector with both angles added together."
        },
        "comment": "Adds this vector to another vector."
      },
      {
        "params": [
          {
            "type": "float",
            "name": "angle",
            "comment": "The angle to add to both of the vector's angles."
          }
        ],
        "return": {
          "type": "{this}",
          "comment": "The vector with the angles added to the input."
        },
        "comment": "Adds this vector's angles to another angle."
      }
    ],
    "normalized": {
      "return": {
        "type": "{this}",
        "comment": "The normalized vector."
      },
      "comment": "Normalizes this vector, dividing the angles by its magnitude."
    },
    "length": {
      "return": {
        "type": "float",
        "comment": "The magnitude or length of this Vector."
      },
      "comment": "Fetches the magnitude or length of this 2D Vector."
    },
    "lengthSquared": {
      "return": {
        "type": "float",
        "comment": "The magnitude or length of this Vector, squared."
      },
      "comment": "Fetches the magnitude or length of this 2D Vector, squared."
    },
    "distanceToSqr": {
      "params": [
        {
          "type": "{this}",
          "name": "vector",
          "comment": "The other vector to use."
        }
      ],
      "return": {
        "type": "float",
        "comment": "The distance between this vector and the other vector."
      },
      "comment": "Calculates the distance between this vector and the other vector."
    },
    "negated": {
      "return": {
        "type": "{this}",
        "comment": "The negated Vector."
      },
      "comment": "Negates this 2D Vector, setting the angles to negative if positive and vice-versa."
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/network/chat/ThrowingComponent.json
{
  "class": {
    "type": "class",
    "extends": "java.lang.Exception",
    "comment": "A @(component)-related exception thrown "
  },
  "fields": {
    "component": {
      "type": "component",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The component involved in this Exception."
    }
  },
  "constructors": [
    {
      "params": [
        {
          "type": "component",
          "name": "component",
          "comment": "The component involved in this Exception."
        }
      ],
      "comment": "Constructs a new ThrowingComponent."
    },
    {
      "params": [
        {
          "type": "component",
          "name": "component",
          "comment": "The component involved in this Exception."
        },
        {
          "type": "java.lang.Throwable",
          "name": "cause",
          "comment": "The cause of this ThrowingComponent."
        }
      ],
      "comment": "Constructs a new ThrowingComponent."
    }
  ],
  "methods": {
    "getComponent": {
      "$getter": "component"
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/nbt/LongArrayTag.json
{
  "class": {
    "type": "class",
    "extends": "net.minecraft.nbt.CollectionTag<net.minecraft.nbt.LongTag>",
    "comment": "Represents a NBT Tag for long arrays."
  },
  "fields": {
    "SELF_SIZE_IN_BYTES": {
      "type": "int",
      "visibility": "private",
      "mods": ["static", "final"],
      "value": "24",
      "comment": "The size in bytes of a @(wlong)[] tag."
    },
    "TYPE": {
      "type": "net.minecraft.nbt.TagType<{this}>",
      "mods": ["static", "final"],
      "comment": "The type of tag this class represents."
    },
    "data": {
      "type": "long[]",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The value of this tag as a long array."
    }
  },
  "constructors": [
    {
      "params": [
        {
          "type": "long[]",
          "name": "data",
          "comment": "The value of this tag as a long array."
        }
      ],
      "comment": "Constructs a new long array tag with the given value."
    },
    {
      "params": [
        {
          "type": "java.util.List<wlong>",
          "name": "data",
          "comment": "The value of this tag as a list of longs."
        }
      ],
      "comment": "Constructs a new long array tag with the given value."
    }
  ],
  "methods": {
    "toArray": {
      "visibility": "private",
      "mods": ["static"],
      "params": [
        {
          "type": "java.util.List<wlong>",
          "name": "data",
          "comment": "The list of longs to convert to an array."
        }
      ],
      "return": {
        "type": "long[]",
        "comment": "The given list as an array."
      },
      "comment": "Converts the given list of longs to an array."
    },
    "getAsLongArray": {
      "$getter": "data"
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/network/chat/TextColor.json
{
  "class": {
    "type": "class",
    "mods": ["final"],
    "comment": "Utility class for handling text colors with @(component)s."
  },
  "fields": {
    "CUSTOM_COLOR_PREFIX": {
      "type": "string",
      "visibility": "private",
      "mods": ["static", "final"],
      "value": "#",
      "comment": "The prefix for using custom colors."
    },
    "CODEC": {
      "type": "codec<{this}>",
      "mods": ["static", "final"],
      "comment": "A codec that serializes a TextColor."
    },
    "LEGACY_FORMAT_TO_COLOR": {
      "type": "map<net.minecraft.ChatFormatting, {this}>",
      "visibility": "private",
      "mods": ["static", "final"],
      "comment": "A Map that converts a @(net.minecraft.ChatFormatting) enum to this class."
    },
    "NAMED_COLORS": {
      "type": "map<string, {this}>",
      "visibility": "private",
      "mods": ["static", "final"],
      "comment": "A Map that has this class color's name to its object reference."
    },
    "value": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The RGB value of this TextColor."
    },
    "name": {
      "type": "string",
      "mods": ["final"],
      "annotations": [
        {
          "type": "nullable"
        }
      ],
      "comment": "The name of this TextColor, or null if it doesn't have one."
    },
    "format": {
      "type": "net.minecraft.ChatFormatting",
      "mods": ["final"],
      "annotations": [
        {
          "type": "nullable"
        }
      ],
      "comment": "The legacy format that this TextColor represents, or null if it doesn't represent one."
    }
  },
  "constructors": [
    {
      "visibility": "private",
      "params": [
        {
          "type": "int",
          "name": "value",
          "comment": "The RGB value of this TextColor."
        },
        {
          "type": "string",
          "name": "name",
          "comment": "The name of this TextColor."
        },
        {
          "type": "net.minecraft.ChatFormatting",
          "name": "format",
          "comment": "The legacy format that this TextColor represents."
        }
      ],
      "comment": "Constructs a new TextColor."
    },
    {
      "visibility": "private",
      "params": [
        {
          "type": "int",
          "name": "value",
          "comment": "The RGB value of this TextColor."
        }
      ],
      "comment": "Constructs a new TextColor."
    }
  ],
  "methods": {
    "getValue": {
      "$getter": "value"
    },
    "serialize": {
      "return": {
        "type": "string",
        "comment": "The serialized string that represents this TextColor."
      },
      "comment": "Serializes this object into a String."
    },
    "formatValue": {
      "visibility": "private",
      "return": {
        "type": "string",
        "comment": "The formatted value of @({this}#value)."
      },
      "comment": "Formats the RGB value of this TextColor."
    },
    "fromLegacyFormat": {
      "mods": ["static"],
      "params": [
        {
          "type": "net.minecraft.ChatFormatting",
          "name": "format",
          "comment": "The format to search with."
        }
      ],
      "return": {
        "type": "{this}",
        "comment": "The TextColor that represents the legacy format, or null if not found."
      },
      "annotations": [
        {
          "type": "nullable"
        }
      ],
      "comment": "Converts a @(net.minecraft.ChatFormatting) to a @({this})."
    },
    "fromRgb": {
      "mods": ["static"],
      "return": {
        "type": "{this}",
        "comment": "The constructed TextColor."
      },
      "comment": "Constructs a TextColor with the given RGB code."
    },
    "parseColor": {
      "mods": ["static"],
      "params": [
        {
          "type": "string",
          "name": "s",
          "comment": "The color string to parse."
        }
      ],
      "annotations": [
        {
          "type": "nullable"
        }
      ],
      "return": {
        "type": "{this}",
        "comment": "The constructed TextColor."
      },
      "comment": "Parses a color string into a TextColor object."
    }
  }
}

=== Team-Inceptus/InceptusNMS/docs/net/minecraft/core/Direction$AxisDirection.json
{
  "class": {
    "type": "enum",
    "enclosing": "net.minecraft.core.Direction",
    "comment": "Represents a direction of an @(net.minecraft.core.Direction$Axis) in 3D Space."
  },
  "enumerations": [
    {
      "name": "POSITIVE",
      "comment": "The positive direction along this axis."
    },
    {
      "name": "NEGATIVE",
      "comment": "The negative direction along this axis."
    }
  ],
  "fields": {
    "step": {
      "type": "int",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The step value of this direction."
    },
    "name": {
      "type": "string",
      "visibility": "private",
      "mods": ["final"],
      "comment": "The description of this direction."
    }
  },
  "constructors": [
    {
      "params": [
        {
          "name": "step",
          "type": "int",
          "comment": "The step value of this direction."
        },
        {
          "name": "name",
          "type": "string",
          "comment": "The description of this direction."
        }
      ],
      "comment": "Constructs a new direction with the given step value and description."
    }
  ],
  "methods": {
    "getStep": {
      "$getter": "step"
    },
    "getName": {
      "$getter": "name"
    },
    "opposite": {
      "return": {
        "type": "{this}",
        "comment": "The opposite axis direction."
      },
      "comment": "Returns the opposite direction along this axis."
    }
  }
}
